// Generated by gencpp from file marvin/lidar.msg
// DO NOT EDIT!


#ifndef MARVIN_MESSAGE_LIDAR_H
#define MARVIN_MESSAGE_LIDAR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace marvin
{
template <class ContainerAllocator>
struct lidar_
{
  typedef lidar_<ContainerAllocator> Type;

  lidar_()
    : id(0)
    , data(0)  {
    }
  lidar_(const ContainerAllocator& _alloc)
    : id(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint64_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::marvin::lidar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marvin::lidar_<ContainerAllocator> const> ConstPtr;

}; // struct lidar_

typedef ::marvin::lidar_<std::allocator<void> > lidar;

typedef boost::shared_ptr< ::marvin::lidar > lidarPtr;
typedef boost::shared_ptr< ::marvin::lidar const> lidarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marvin::lidar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marvin::lidar_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace marvin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'marvin': ['/home/hariank/mARVin/catkin_ws/src/marvin/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::marvin::lidar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marvin::lidar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marvin::lidar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marvin::lidar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marvin::lidar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marvin::lidar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marvin::lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6bdfa24e970e7ffd91c15653cd88be54";
  }

  static const char* value(const ::marvin::lidar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6bdfa24e970e7ffdULL;
  static const uint64_t static_value2 = 0x91c15653cd88be54ULL;
};

template<class ContainerAllocator>
struct DataType< ::marvin::lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marvin/lidar";
  }

  static const char* value(const ::marvin::lidar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marvin::lidar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n\
uint64 data\n\
";
  }

  static const char* value(const ::marvin::lidar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marvin::lidar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lidar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marvin::lidar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marvin::lidar_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "data: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARVIN_MESSAGE_LIDAR_H
